//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PX.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class FileTemplate
    {
        public FileTemplate()
        {
            this.FileTemplates1 = new HashSet<FileTemplate>();
            this.Pages = new HashSet<Page>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Content { get; set; }
        public string Controller { get; set; }
        public string Action { get; set; }
        public string Parameters { get; set; }
        public Nullable<int> PageTemplateId { get; set; }
        public Nullable<int> ParentId { get; set; }
        public string Hierarchy { get; set; }
        public int RecordOrder { get; set; }
        public bool RecordActive { get; set; }
        public System.DateTime Created { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> Updated { get; set; }
        public string UpdatedBy { get; set; }
    
        public virtual PageTemplate PageTemplate { get; set; }
        public virtual ICollection<FileTemplate> FileTemplates1 { get; set; }
        public virtual FileTemplate FileTemplate1 { get; set; }
        public virtual ICollection<Page> Pages { get; set; }
    }
}
