//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PX.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupPermission
    {
        public int Id { get; set; }
        public int UserGroupId { get; set; }
        public int PermissionId { get; set; }
        public bool HasPermission { get; set; }
    
        public virtual UserGroup UserGroup { get; set; }
    }
}
