//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PX.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Page
    {
        public Page()
        {
            this.Pages1 = new HashSet<Page>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string Caption { get; set; }
        public string CaptionWorking { get; set; }
        public string Content { get; set; }
        public string ContentWorking { get; set; }
        public string FriendlyUrl { get; set; }
        public Nullable<int> PageTemplateId { get; set; }
        public int Status { get; set; }
        public bool IsHomePage { get; set; }
        public string Hierarchy { get; set; }
        public Nullable<int> ParentId { get; set; }
        public int RecordOrder { get; set; }
        public bool RecordActive { get; set; }
        public System.DateTime Created { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> Updated { get; set; }
        public string UpdatedBy { get; set; }
    
        public virtual ICollection<Page> Pages1 { get; set; }
        public virtual Page Page1 { get; set; }
        public virtual PageTemplate PageTemplate { get; set; }
    }
}
