//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PX.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PageTemplate
    {
        public PageTemplate()
        {
            this.FileTemplates = new HashSet<FileTemplate>();
            this.Pages = new HashSet<Page>();
            this.PageTemplates1 = new HashSet<PageTemplate>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Content { get; set; }
        public string Hierarchy { get; set; }
        public Nullable<int> ParentId { get; set; }
        public int RecordOrder { get; set; }
        public bool RecordActive { get; set; }
        public System.DateTime Created { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> Updated { get; set; }
        public string UpdatedBy { get; set; }
    
        public virtual ICollection<FileTemplate> FileTemplates { get; set; }
        public virtual ICollection<Page> Pages { get; set; }
        public virtual ICollection<PageTemplate> PageTemplates1 { get; set; }
        public virtual PageTemplate PageTemplate1 { get; set; }
    }
}
