//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PX.EntityModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PXHotelEntities : DbContext
    {
        public PXHotelEntities()
            : base("name=PXHotelEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<BookingRequest> BookingRequests { get; set; }
        public DbSet<Country> Countries { get; set; }
        public DbSet<GroupPermission> GroupPermissions { get; set; }
        public DbSet<Language> Languages { get; set; }
        public DbSet<LocalizedResource> LocalizedResources { get; set; }
        public DbSet<Menu> Menus { get; set; }
        public DbSet<News> News { get; set; }
        public DbSet<NewsCategory> NewsCategories { get; set; }
        public DbSet<NewsNewsCategory> NewsNewsCategories { get; set; }
        public DbSet<Page> Pages { get; set; }
        public DbSet<PageTemplate> PageTemplates { get; set; }
        public DbSet<Room> Rooms { get; set; }
        public DbSet<RoomType> RoomTypes { get; set; }
        public DbSet<SettingType> SettingTypes { get; set; }
        public DbSet<SiteSetting> SiteSettings { get; set; }
        public DbSet<Template> Templates { get; set; }
        public DbSet<Testimonial> Testimonials { get; set; }
        public DbSet<UserGroup> UserGroups { get; set; }
        public DbSet<User> Users { get; set; }
    }
}
